### ISSUE TITLE
Timeout for large files.

### ISSUE THREAD

**Issue by Luphaestus** [khushpanchal/Ketch#23] opened 2024-08-21 13:53 UTC
Hi,

I'm having trouble downloading large files (like 700MB+) in my app. No matter which file hosting service I use (Google, Mediafire, GitHub), the downloads keep timing out. The problem happens both in my app and the sample app.

Example Link:
[Download Link](https://github.com/Luphaestus/VulcanUpdate/raw/main/Twrp/VulcanUpdate/VulcanV2.1.zip)

Is this a problem on my end? 

Thanks!

**Comment by khushpanchal** [comment] 2024-08-21 14:09
Have you tried increasing readTimout.

Currently it is set to 10 seconds by default.

Could try setting it to atleast 30 seconds.

To customize timeout, pass Download config while initialising the library

**Comment by Luphaestus** [comment] 2024-08-21 14:47
Thank you for you quick reply, Unfortunately, it still doesn't work. Is there a way I can more logs?

**Comment by khushpanchal** [comment] 2024-08-21 16:20
Does timeout happens in between download or it in the start only?

Also what exact failureReason you are getting?

**Comment by Luphaestus** [comment] 2024-08-21 17:47
I'm not exactly sure what you mean, but I don't get a single progress update.

And the exact failure reason is "timeout"

**Comment by khushpanchal** [comment] 2024-08-21 18:55
Let me check and get back.

**Comment by khushpanchal** [comment] 2024-09-21 12:22
@Luphaestus I am not able to reproduce it. I am able to download raw large files. Could you check if the raw file links you are usind are correct? E.g google drive doesn't provide raw file link for very large files. 
Closing the issue for now.

**Closed by khushpanchal** 2024-09-21 12:22 UTC
